--1.Cleanup
Delete from rsd_dm_dev_load.matillion.source_columns where source_table_name='';
Delete from rsd_dm_dev_load.matillion.table_pk where source_table_name='';
Delete from rsd_dm_dev_load.matillion.target_columns where source_table_name='';
Delete from rsd_dm_dev_load.matillion.target_column_datatype_full where source_table_name='';
Delete from rsd_dm_dev_load.matillion.main_attributes where source_table_name='';
Delete from rsd_dm_dev_load.matillion.create_table_script where source_table_name='';

--2.Source_columns
Select
'application_name' as application_name,
'load_name' as load_name,
'source_sys_name' as source_sys_name,
'orchestration_sub_name' as orchestration_sub_name,
TABLE_NAME AS SOURCE_TABLE_NAME,
'MSSQL_TO_LOD' AS LOAD_TYPE,
UPPER(TABLE_CATALOG) AS SOURCE_DATABASE_NAME,
UPPER(TABLE_SCHEMA) AS SOURCE_SCHEMA_NAME,
UPPER(COLUMN_NAME) AS SOURCE_COLUMN_NAME,
UPPER(DATA_TYPE) AS SOURCE_DATATYPE,
CASE WHEN DATA_TYPE IN ('NUMBER','DECIMAL','MONEY','SMALLMONEY') THEN UPPER(ISNULL(convert(varchar,NUMERIC_PERCISION),'')) ELSE ISNULL(convert(varchar,CHARACTER_MAXIMUM_LENGTH),'') END AS SOURCE_LENGTH,
CASE WHEN DATA_TYPE IN ('NUMBER','DECIMAL','MONEY','SMALLMONEY') THEN UPPER(NUMERIC_SCALE) ELSE '' END AS SOURCE_SCALE,
ORDINAL_POSITION,
CASE WHEN IS_NULLABLE='NO' THEN 'NOT NULL' ELSE 'NULL' END AS IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='SOURCE_TABLE_NAME'
AND TABLE_SCHEMA='SOURCE_SCHEMA_NAME'

--3.TABLE_PK
SELECT DISTINCT('SOURCE_TABLE_NAME') AS SOURCE_TABLE_NAME, A.COLUMN_NAME AS COLUMN_NAME
FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE A,INFORMATION_SCHEMA.TABLE_CONSTRAINTS B
WHERE A.TABLE_NAME='SOURCE_TABLE_NAME'
AND A.TABLE_NAME=B.TABLE_NAME AND A.CONSTRAINT_NAME=B.CONSTRAINT_NAME
AND B.CONSTRAIN_TYPE IN ('PRIMARY KEY')
AND A.TABLE_SCHEMA='SOURCE_TABLE_NAME'

--4.TARGET_COLUMNS
INSERT INTO RSD_DM_DEV_LOAD.MATILLION.TARGET_COLUMNS
SELECT 'SOURCE_TABLE_NAME' AS SOURCE_TABLE_NAME,
'SM' AS TRANSFORMATION,
'RSD_DM' AS TARGET_DATABASE_NAME,
'MATILLON' AS TARGET_SCHEMA_NAME,
'TEMP_LIFE'||'SOURCE_SYS_NAME'||'SOURCE_TABLE_NAME' AS TARGET_TABLE_NAME,
'SOURCE_SYS_NAME' AS SOURCE_SYS_NAME,
SOURCE_COLUMN_NAME AS TARGET_COLUMN_NAME,
ORDINAL_POSITION AS TARGET_COL_SEQ_NO,
CASE WHEN UPPER(SOURCE_DATATYPE) IN ('CHAR','NVARCHAR','TEXT') THEN 'VARCHAR'
WHEN UPPER(SOURCE_DATATYPE) IN ('DATE') THEN 'DATE'
WHEN UPPER(SOURCE_DATATYPE) IN ('DATETIME','SMALLDATETIME') THEN 'TIMESTAMP_NTZ'
WHEN UPPER(SOURCE_DATATYPE) IN ('INT','SMALLINT','BIGINT','FLOAT','TINYINT','REAL') THEN 'NUMBER'
WHEN UPPER(SOURCE_DATATYPE) IN ('NUMBER','DECIMAL','MONEY','SMALLMONEY') THEN 'NUMBER'
ELSE UPPER(SOURCE_DATATYPE) END AS TARGET_DATATYPE,
CASE WHEN SOURCE_LENGTH='-1' THEN '16777216' WHEN UPPER(SOURCE_DATATYPE) IN ('INT','SMALLINT','BIGINT','FLOAT','TINYINT','REAL') AND SOURCE_LENGTH='' THEN '38' ELSE IFNULL(SOURCE_LENGTH,'') END AS TARGET_LENGTH,
CASE WHEN UPPER(SOURCE_DATATYPE) IN ('INT','SMALLINT','BIGINT','FLOAT','TINYINT','REAL') AND SOURCE_SCALE='' THEN '0' ELSE SOURCE_SCALE END AS TARGET_SCALE,
CASE WHEN SOURCE_COLUMN_NAME IN (SELECT COLUMN_NAME FROM RSD_DM_DEV_LOAD.MATILLION.TABLE_PK) THEN 'Y' ELSE '' END AS TARGET_PRIMARY_KEY,
'' AS TARGET_DEFAULT_VALUE,
'Y' AS ACTIVE_IND,
C.COLUMN_DESC AS NOTE,
'J_D_JOB_NAME' AS ORCHESTRATION_JOB_NAME,
IS_NULLABLE
FROM RSD_DM_DEV_LOAD.MATILLION.SOURCE_COLUMNS S
LEFT JOIN RSD_DM_DEV_PUBLISH.GLOBAL.COLLIBRA_DATA C ON
S.SOURCE_TABLE_NAME=C.TABLE_NAME AND 
S.SOURCE_COLUMN_NAME=C.COLUMN_NAME
WHERE S.SOURCE_TABLE_NAME='SOURCE_TABLE_NAME'

--5.TARGET_COLUMN_DATATYPE_FULL
INSERT INRO RSD_DM_DEV_LOAD.MATILLION.TARGET_COLUMN_DATATYPE_FULL
SELECT *, 
CASE WHEN TARGET_DATATYPE='NUMBER' THEN TARGET_DATATYPE||'('||TARGET_LENGTH||','||TARGET_SCALE||')'
WHEN TARGET_DATATYPE='TIMESTAMP_NTZ' THEN 'TIMESTAMP_NTZ(9)'
ELSE UPPER(TARGET_DATATYPE)||IFNULL('('||TARGET_LENGTH||')','')
END AS COLUMN_DATATYPE_FULL
FROM RSD_DM_DEV_LOAD.MATILLION.TARGET_COLUMNS
WHERE SOURCE_TABLE_NAME='SOURCE_TABLE_NAME'

--6.CREATE TABLE SCRIPT
INSERT INTO RSD_DM_DEV_LOAD.MATILLION.create_table_script(SOURCE_TABLE_NAME,SCRIPT_LINE)
SELECT 'SOURCE_TABLE_NAME' AS SOURCE_TABLE_NAME, SCRIPT_LINE AS SCRIPT_LINE FROM (
    SELECT * FROM(
        SELECT 1 AS SEQ,0 AS TARGET_COL_SEQ_NO,'CREATE OR REPLACE TABLE'||(SELECT TOP 1 TARGET_DATABASE_NAME||'.'||TARGET_SCHEMA_NAME||'.'||TARGET_TABLE_NAME FROM RSD_DM_DEV_LOAD.MATILLION.TARGET_COLUMN_DATATYPE_FULL WHERE SOURCE_TABLE_NAME='SOURCE_TABLE_NAME')||'(' AS SCRIPT_LINE
        UNION ALL,
        SELECT 2 AS SEQ,TARGET_COL_SEQ_NO,
        UPPER(TARGET_COLUMN_NAME)||' '||COLUMN_DATATYPE_FULL||' '||IS_NULLABLE||IFF(IFNULL(NOTE,'')='','','COMMENT'''||NOTE)||''','AS SCRIPT_LINE
        FROM RSD_DM_DEV_LOAD.MATILLION.TARGET_COLUMN_DATATYPE_FULL A WHERE A.SOURCE_TABLE_NAME='SOURCE_TABLE_NAME'
        UNION ALL
        SELECT 4 AS SEQ,100,');' AS SCRIPT_LINE
    )ORDER BY 1,2
)

